# Generated by Django 3.1.7 on 2022-05-15 04:40

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('street', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('order_list', models.CharField(max_length=1000)),
                ('order_total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('name_on_card', models.CharField(max_length=30)),
                ('credit_card_number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')])),
                ('cvv_number', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')])),
                ('billing_street', models.CharField(max_length=35)),
                ('billing_city', models.CharField(max_length=35)),
                ('billing_state', models.CharField(max_length=35)),
                ('billing_postal_code', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(code='invalid_input', message='Must be numeric', regex='^[0-9]*$')])),
                ('charge_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('tshirt_id', models.AutoField(primary_key=True, serialize=False)),
                ('tshirt_name', models.CharField(max_length=30)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('inventory', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
