# Generated by Django 3.1.7 on 2022-05-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lite_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cvv_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name_on_card',
        ),
    ]
